map_type: costmap

origin_x: 0
origin_y: 0

resolution: 0.2

global_frame: map
robot_base_frame: robot_footprint

obstacle_range: 2.5 
raytrace_range: 3.0 

transform_tolerance: 1.0

footprint: [[0.2, 0.1], [-0.2, 0.1], [-0.2, -0.1], [0.2, -0.1]]
inflation_radius: 1.25
cost_scaling_factor: 2.5 

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /adam_bot/laser/scan, marking: true, clearing: true}

