global_costmap:
   global_frame: map
   robot_base_frame: robot_footprint
   update_frequency: 2.0
   publish_frequency: 2.0
   width: 40.0
   height: 40.0
   resolution: 0.02
   static_map: true
   cost_factor: 0.55
   neutral_cost: 66
   lethal_cost: 253
   rolling_window: false
